### ISSUE TITLE
The name 'Regex' does not exist in the current context

### ISSUE THREAD

**Issue by jd3141** [FalconForceTeam/SOAPHound#5]
Build output: 
`SOAPHound\ADWS\ADWSConnector.cs(67,20,67,25): error CS0103: The name 'Regex' does not exist in the current context`
`SOAPHound\ADWS\ADWSConnector.cs(67,46,67,58): error CS0103: The name 'RegexOptions' does not exist in the current context`

**Comment by xennn** [comment]
i have the same error

**Comment by 0xFF-NK** [comment]
fixed

**Comment by jd3141** [comment]
OK, it builds now. Thanks.
